name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint code
        run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4

      - name: Check out code
        uses: actions/checkout@v3

      - name: Format code
        run: make format

      - name: Check for local changes
        run: git diff --exit-code
